[lint.pycodestyle]
ignore-overlong-task-comments = true
max-doc-length = 89

[tool.black]
line-length = 89
target-version = 'py310'

[tool.ruff]
extend = "pyproject.global.toml"
fix = true
line-length = 89
output-format = "full"
target-version = "py310"
lint.extend-ignore = [
  "INP001",
  "S311",
  "N815"
]
