[lint.pycodestyle]
ignore-overlong-task-comments = true
max-doc-length = 89

[tool.black]
line-length = 89
target-version = 'py310'

[tool.ruff]
exclude = [
  "src/k8proxy/projects/taxi/game/base.py"
]
extend = "pyproject.global.toml"
fix = true
line-length = 89
output-format = "full"
target-version = "py310"
lint.extend-ignore = [
  "INP001",
  "S311",
  "N815"
]

[tool.ruff.per-file-ignores]
"tests/*" = ["ARG001", "ARG002", "ERA001", "F811", "PLR2004", "S101", "SIM102", "T201"]
